In [2]:
from datetime import datetime

import pandas as pd

In [3]:
start_date = datetime(2025, 1, 1)
end_date = datetime(2030, 12, 31)

date_range = pd.date_range(start_date, end_date)

date_df = pd.DataFrame(date_range, columns=["date"])

In [4]:
date_df.head()

        date
0 2025-01-01
1 2025-01-02
2 2025-01-03
3 2025-01-04
4 2025-01-05

In [5]:
date_df["year"] = date_df["date"].dt.year
date_df["months"] = date_df["date"].dt.month
date_df["day"] = date_df["date"].dt.day
date_df["day_of_week"] = date_df["date"].dt.day_of_week + 1
date_df["is_weekend"] = date_df["day_of_week"].isin([6,7])

In [7]:
date_df.sample(10)

           date  year  months  day  day_of_week  is_weekend
1983 2030-06-07  2030       6    7            5       False
1337 2028-08-30  2028       8   30            3       False
1720 2029-09-17  2029       9   17            1       False
1153 2028-02-28  2028       2   28            1       False
787  2027-02-27  2027       2   27            6        True
1677 2029-08-05  2029       8    5            7        True
990  2027-09-18  2027       9   18            6        True
772  2027-02-12  2027       2   12            5       False
652  2026-10-15  2026      10   15            4       False
1794 2029-11-30  2029      11   30            5       False

In [8]:
date_df.to_csv("date_master.csv", index=False)